{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "8f712504",
   "metadata": {},
   "source": [
    "-- Creating tables for PH-EmployeeDB\n",
    "CREATE TABLE departments (\n",
    "\tdept_no VARCHAR NOT NULL,\n",
    "\tdept_name VARCHAR(40) NOT NULL,\n",
    "\tPRIMARY KEY (dept_no),\n",
    "\tUNIQUE (dept_name)\n",
    ");\n",
    "\n",
    "CREATE TABLE employees (\n",
    "\temp_no INT NOT NULL,\n",
    "\tbirth_date DATE NOT NULL,\n",
    "\tfirst_name VARCHAR NOT NULL,\n",
    "\tlast_name VARCHAR NOT NULL,\n",
    "\tgender VARCHAR NOT NULL,\n",
    "\thire_date DATE NOT NULL,\n",
    "\tPRIMARY KEY (emp_no)\n",
    ");\n",
    "\n",
    "CREATE TABLE dept_emp (\n",
    "\temp_no INT NOT NULL,\n",
    "\tdept_no VARCHAR NOT NULL,\n",
    "    from_date DATE NOT NULL,\n",
    "    to_date DATE NOT NULL,\n",
    "    FOREIGN KEY (emp_no) REFERENCES employees (emp_no),\n",
    "    FOREIGN KEY (dept_no) REFERENCES departments (dept_no),\n",
    "    PRIMARY KEY (emp_no, dept_no)\n",
    ");\n",
    "\n",
    "CREATE TABLE dept_manager (\n",
    "    dept_no VARCHAR NOT NULL,\n",
    "    emp_no INT NOT NULL,\n",
    "    from_date DATE NOT NULL,\n",
    "    to_date DATE NOT NULL,\n",
    "    FOREIGN KEY (emp_no) REFERENCES employees (emp_no),\n",
    "    FOREIGN KEY (dept_no) REFERENCES departments (dept_no),\n",
    "    PRIMARY KEY (emp_no, dept_no)\n",
    ");\n",
    "\n",
    "CREATE TABLE salaries (\n",
    "\temp_no INT NOT NULL,\n",
    "\tsalary INT NOT NULL,\n",
    "\tfrom_date DATE NOT NULL,\n",
    "\tto_date DATE NOT NULL,\n",
    "\tFOREIGN KEY (emp_no) REFERENCES employees (emp_no),\n",
    "\tPRIMARY KEY (emp_no)\n",
    ");\n",
    "\n",
    "CREATE TABLE titles (\n",
    "\temp_no INT NOT NULL,\n",
    "    title VARCHAR(50) NOT NULL,\n",
    "    from_date DATE NOT NULL,\n",
    "    to_date DATE,\n",
    "    FOREIGN KEY(emp_no) REFERENCES employees (emp_no),\n",
    "    PRIMARY KEY (emp_no, title, from_date)\n",
    ");\n",
    "\n",
    "COPY departments FROM '/Users/hemantkiri/Public/departments.csv' DELIMITER ',' CSV HEADER;\n",
    "COPY employees FROM '/Users/hemantkiri/Public/employees.csv' DELIMITER ',' CSV HEADER;\n",
    "COPY dept_emp FROM '/Users/hemantkiri/Public/dept_emp.csv' DELIMITER ',' CSV HEADER;\n",
    "COPY dept_manager FROM '/Users/hemantkiri/Public/dept_manager.csv' DELIMITER ',' CSV HEADER;\n",
    "COPY salaries FROM '/Users/hemantkiri/Public/salaries.csv' DELIMITER ',' CSV HEADER;\n",
    "COPY titles FROM '/Users/hemantkiri/Public/titles.csv' DELIMITER ',' CSV HEADER;\n",
    "\n",
    "-- Determine Retirement Eligibility\n",
    "\tSELECT first_name, last_name\n",
    "\tFROM employees\n",
    "\tWHERE birth_date BETWEEN '1952-01-01' AND '1955-12-31';\n",
    "\n",
    "\tSELECT first_name, last_name\n",
    "\tFROM employees\n",
    "\tWHERE birth_date BETWEEN '1952-01-01' AND '1952-12-31';\n",
    "\n",
    "\tSELECT first_name, last_name\n",
    "\tFROM employees\n",
    "\tWHERE birth_date BETWEEN '1953-01-01' AND '1953-12-31';\n",
    "\n",
    "\tSELECT first_name, last_name\n",
    "\tFROM employees\n",
    "\tWHERE birth_date BETWEEN '1954-01-01' AND '1954-12-31';\n",
    "\n",
    "\tSELECT first_name, last_name\n",
    "\tFROM employees\n",
    "\tWHERE birth_date BETWEEN '1955-01-01' AND '1955-12-31';\n",
    "\n",
    "-- Retirement eligibility\n",
    "\tSELECT first_name, last_name\n",
    "\tFROM employees\n",
    "\tWHERE birth_date BETWEEN '1952-01-01' AND '1955-12-31';\n",
    "\n",
    "\tSELECT first_name, last_name\n",
    "\tFROM employees\n",
    "\tWHERE hire_date BETWEEN '1985-01-01' AND '1988-12-31';\n",
    "\n",
    "-- Retirement eligibility\n",
    "\tSELECT first_name, last_name\n",
    "\tFROM employees\n",
    "\tWHERE (birth_date BETWEEN '1952-01-01' AND '1955-12-31')\n",
    "\tAND (hire_date BETWEEN '1985-01-01' AND '1988-12-31');\n",
    "\n",
    "-- Number of employees retiring\n",
    "\tSELECT COUNT(first_name)\n",
    "\tFROM employees\n",
    "\tWHERE (birth_date BETWEEN '1952-01-01' AND '1955-12-31')\n",
    "\tAND (hire_date BETWEEN '1985-01-01' AND '1988-12-31');\n",
    "\n",
    "\tSELECT first_name, last_name\n",
    "\tINTO retirement_info\n",
    "\tFROM employees\n",
    "\tWHERE (birth_date BETWEEN '1952-01-01' AND '1955-12-31')\n",
    "\tAND (hire_date BETWEEN '1985-01-01' AND '1988-12-31');\n",
    "\tDROP TABLE retirement_info;\n",
    "\n",
    "-- Create new table for retiring employees\n",
    "\tSELECT emp_no, first_name, last_name\n",
    "\tINTO retirement_info\n",
    "\tFROM employees\n",
    "\tWHERE (birth_date BETWEEN '1952-01-01' AND '1955-12-31')\n",
    "\tAND (hire_date BETWEEN '1985-01-01' AND '1988-12-31');\n",
    "-- Check the table\n",
    "\tSELECT * FROM retirement_info;\n",
    "\n",
    "-- Joining departments and dept_manager tables\n",
    "\tSELECT departments.dept_name,\n",
    "\tdept_manager.emp_no,\n",
    "\tdept_manager.from_date,\n",
    "\tdept_manager.to_date\n",
    "\tFROM departments\n",
    "\tINNER JOIN dept_manager\n",
    "\tON departments.dept_no = dept_manager.dept_no;\n",
    "\n",
    "-- Joining retirement_info and dept_emp tables\n",
    "\tSELECT retirement_info.emp_no,\n",
    "    retirement_info.first_name,\n",
    "\tretirement_info.last_name,\n",
    "    dept_emp.to_date\n",
    "\tFROM retirement_info\n",
    "\tLEFT JOIN dept_emp\n",
    "\tON retirement_info.emp_no = dept_emp.emp_no;\n",
    "\n",
    "--shortened to a nickname\n",
    "\tSELECT ri.emp_no,\n",
    "    ri.first_name,\n",
    "    ri.last_name,\n",
    "    de.to_date\n",
    "\tFROM retirement_info as ri\n",
    "\tLEFT JOIN dept_emp as de\n",
    "\tON ri.emp_no = de.emp_no;\n",
    "\n",
    "-- Joining departments and dept_manager tables\n",
    "\tSELECT departments.dept_name,\n",
    "\tdept_manager.emp_no,\n",
    "\tdept_manager.from_date,\n",
    "\tdept_manager.to_date\n",
    "\tFROM departments\n",
    "\tINNER JOIN dept_manager\n",
    "\tON departments.dept_no = dept_manager.dept_no;\n",
    "\n",
    "--shortened to a nickname\n",
    "\tSELECT d.dept_name,\n",
    "\tdm.emp_no,\n",
    "\tdm.from_date,\n",
    "\tdm.to_date\n",
    "\tFROM departments as d\n",
    "\tINNER JOIN dept_manager as dm\n",
    "\tON d.dept_no = dm.dept_no;\n",
    "\n",
    "\tSELECT ri.emp_no,\n",
    "    ri.first_name,\n",
    "    ri.last_name,\n",
    "    de.to_date\n",
    "\tINTO current_emp\n",
    "\tFROM retirement_info as ri\n",
    "\tLEFT JOIN dept_emp as de\n",
    "\tON ri.emp_no = de.emp_no\n",
    "\tWHERE de.to_date = ('9999-01-01');\n",
    "    SELECT * FROM current_emp;\n",
    "\n",
    "-- Employee count by department number\n",
    "\tSELECT COUNT(ce.emp_no), de.dept_no\n",
    "\tFROM current_emp as ce\n",
    "\tLEFT JOIN dept_emp as de\n",
    "\tON ce.emp_no = de.emp_no\n",
    "\tGROUP BY de.dept_no;\n",
    "\n",
    "-- Employee count by department number\n",
    "\tSELECT COUNT(ce.emp_no), de.dept_no\n",
    "\tFROM current_emp as ce\n",
    "\tLEFT JOIN dept_emp as de\n",
    "\tON ce.emp_no = de.emp_no\n",
    "\tGROUP BY de.dept_no\n",
    "\tORDER BY de.dept_no;\n",
    "\n",
    "\tSELECT * FROM salaries\n",
    "\tORDER BY to_date DESC;\n",
    "\n",
    "\tSELECT emp_no, first_name, last_name\n",
    "\tINTO retirement_info\n",
    "\tFROM employees\n",
    "\tWHERE (birth_date BETWEEN '1952-01-01' AND '1955-12-31')\n",
    "\tAND (hire_date BETWEEN '1985-01-01' AND '1988-12-31');\n",
    "\n",
    "\tSELECT emp_no,\n",
    "    first_name,\n",
    "\tlast_name,\n",
    "    gender\n",
    "\tINTO emp_info\n",
    "\tFROM employees\n",
    "\tWHERE (birth_date BETWEEN '1952-01-01' AND '1955-12-31')\n",
    "\tAND (hire_date BETWEEN '1985-01-01' AND '1988-12-31');\n",
    "\n",
    "\n",
    "\tSELECT e.emp_no,\n",
    "\te.first_name,\n",
    "\te.last_name,\n",
    "    e.gender,\n",
    "    s.salary,\n",
    "    de.to_date\n",
    "--INTO emp_info\n",
    "\tFROM employees as e\n",
    "\tINNER JOIN salaries as s\n",
    "\tON (e.emp_no = s.emp_no)\n",
    "\tINNER JOIN dept_emp as de\n",
    "\tON (e.emp_no = de.emp_no)\n",
    "\tWHERE (e.birth_date BETWEEN '1952-01-01' AND '1955-12-31')\n",
    "    AND (e.hire_date BETWEEN '1985-01-01' AND '1988-12-31')\n",
    "\tAND (de.to_date = '9999-01-01');\n",
    "\n",
    "-- List of managers per department\n",
    "\tSELECT  dm.dept_no,\n",
    "\td.dept_name,\n",
    "\tdm.emp_no,\n",
    "\tce.last_name,\n",
    "\tce.first_name,\n",
    "\tdm.from_date,\n",
    "\tdm.to_date\n",
    "\t--INTO manager_info\n",
    "\tFROM dept_manager AS dm\n",
    "    INNER JOIN departments AS d\n",
    "    ON (dm.dept_no = d.dept_no)\n",
    "    INNER JOIN current_emp AS ce\n",
    "    ON (dm.emp_no = ce.emp_no);\n",
    "\t\t\n",
    "\tSELECT ce.emp_no,\n",
    "\tce.first_name,\n",
    "\tce.last_name,\n",
    "\td.dept_name\n",
    "-- INTO dept_info\n",
    "\tFROM current_emp as ce\n",
    "\tINNER JOIN dept_emp AS de\n",
    "\tON (ce.emp_no = de.emp_no)\n",
    "\tINNER JOIN departments AS d\n",
    "\tON (de.dept_no = d.dept_no);\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b828f105",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "37bb2680",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "PythonData",
   "language": "python",
   "name": "pythondata"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
